# Generated by Django 5.1 on 2024-08-09 00:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_trades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_time_placed',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 8, 9, 0, 1, 33, 875180, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
